// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMIS.Infrastructure.Mobile.Context;

#nullable disable

namespace SMIS.Infrastructure.Mobile.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20260225010643_sdfsflk")]
    partial class sdfsflk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SMIS.Domain.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityState")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSyncedToServer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("IsSyncedToServer");

                    b.HasIndex("LastModifiedUtc");

                    b.HasIndex("ShopId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Code = "BEV",
                            CreatedDate = new DateTime(2026, 2, 25, 1, 6, 42, 771, DateTimeKind.Utc).AddTicks(4540),
                            Description = "Drinks and beverages",
                            EntityState = 0,
                            IsActive = true,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTimeOffset(new DateTime(2026, 2, 25, 1, 6, 42, 771, DateTimeKind.Unspecified).AddTicks(7686), new TimeSpan(0, 0, 0, 0, 0)),
                            LastSyncedAt = new DateTime(2026, 2, 25, 1, 6, 42, 771, DateTimeKind.Utc).AddTicks(3660),
                            Name = "Beverages",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 2, 25, 1, 6, 42, 771, DateTimeKind.Utc).AddTicks(6270),
                            Version = 0
                        },
                        new
                        {
                            Id = "2",
                            Code = "FOOD",
                            CreatedDate = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(1237),
                            Description = "Edible products and snacks",
                            EntityState = 0,
                            IsActive = true,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTimeOffset(new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Unspecified).AddTicks(2821), new TimeSpan(0, 0, 0, 0, 0)),
                            LastSyncedAt = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(374),
                            Name = "Food Items",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(2101),
                            Version = 0
                        },
                        new
                        {
                            Id = "3",
                            Code = "STAT",
                            CreatedDate = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(6994),
                            Description = "Office and school supplies",
                            EntityState = 0,
                            IsActive = true,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTimeOffset(new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Unspecified).AddTicks(8949), new TimeSpan(0, 0, 0, 0, 0)),
                            LastSyncedAt = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(5974),
                            Name = "Stationery",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(7925),
                            Version = 0
                        },
                        new
                        {
                            Id = "4",
                            Code = "GROC",
                            CreatedDate = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(9879),
                            Description = "Daily household items",
                            EntityState = 0,
                            IsActive = true,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTimeOffset(new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Unspecified).AddTicks(9888), new TimeSpan(0, 0, 0, 0, 0)),
                            LastSyncedAt = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(9867),
                            Name = "Grocery",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(9883),
                            Version = 0
                        },
                        new
                        {
                            Id = "5",
                            Code = "CARE",
                            CreatedDate = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(9908),
                            Description = "Health and hygiene products",
                            EntityState = 0,
                            IsActive = true,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTimeOffset(new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Unspecified).AddTicks(9914), new TimeSpan(0, 0, 0, 0, 0)),
                            LastSyncedAt = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(9904),
                            Name = "Personal Care",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(9911),
                            Version = 0
                        },
                        new
                        {
                            Id = "6",
                            Code = "ELEC",
                            CreatedDate = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(9930),
                            Description = "Electronic devices and accessories",
                            EntityState = 0,
                            IsActive = true,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTimeOffset(new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Unspecified).AddTicks(9936), new TimeSpan(0, 0, 0, 0, 0)),
                            LastSyncedAt = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(9926),
                            Name = "Electronics",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 2, 25, 1, 6, 42, 772, DateTimeKind.Utc).AddTicks(9933),
                            Version = 0
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityState")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Translation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityState")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSyncedToServer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationKeyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TranslationKeyId", "LanguageNo")
                        .IsUnique();

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.TranslationKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityState")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSyncedToServer")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MessageCode");

                    b.ToTable("TranslationKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
