// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMIS.Infrastructure.Mobile.Context;

#nullable disable

namespace SMIS.Infrastructure.Mobile.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20260224160137_InitialMobileMigration")]
    partial class InitialMobileMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SMIS.Domain.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityState")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSyncedToServer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("IsSyncedToServer");

                    b.HasIndex("LastModifiedUtc");

                    b.HasIndex("ShopId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Code = "BEV",
                            CreatedDate = new DateTime(2026, 2, 24, 16, 1, 37, 78, DateTimeKind.Utc).AddTicks(9334),
                            Description = "Drinks and beverages",
                            EntityState = 0,
                            IsActive = true,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTimeOffset(new DateTime(2026, 2, 24, 16, 1, 37, 79, DateTimeKind.Unspecified).AddTicks(1166), new TimeSpan(0, 0, 0, 0, 0)),
                            LastSyncedAt = new DateTime(2026, 2, 24, 16, 1, 37, 78, DateTimeKind.Utc).AddTicks(8531),
                            Name = "Beverages",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 2, 24, 16, 1, 37, 78, DateTimeKind.Utc).AddTicks(9971),
                            Version = 0
                        },
                        new
                        {
                            Id = "2",
                            Code = "FOOD",
                            CreatedDate = new DateTime(2026, 2, 24, 16, 1, 37, 79, DateTimeKind.Utc).AddTicks(4924),
                            Description = "Edible products and snacks",
                            EntityState = 0,
                            IsActive = true,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTimeOffset(new DateTime(2026, 2, 24, 16, 1, 37, 79, DateTimeKind.Unspecified).AddTicks(6437), new TimeSpan(0, 0, 0, 0, 0)),
                            LastSyncedAt = new DateTime(2026, 2, 24, 16, 1, 37, 79, DateTimeKind.Utc).AddTicks(3979),
                            Name = "Food Items",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 2, 24, 16, 1, 37, 79, DateTimeKind.Utc).AddTicks(5704),
                            Version = 0
                        },
                        new
                        {
                            Id = "3",
                            Code = "STAT",
                            CreatedDate = new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Utc).AddTicks(79),
                            Description = "Office and school supplies",
                            EntityState = 0,
                            IsActive = true,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTimeOffset(new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Unspecified).AddTicks(2375), new TimeSpan(0, 0, 0, 0, 0)),
                            LastSyncedAt = new DateTime(2026, 2, 24, 16, 1, 37, 79, DateTimeKind.Utc).AddTicks(9061),
                            Name = "Stationery",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Utc).AddTicks(1003),
                            Version = 0
                        },
                        new
                        {
                            Id = "4",
                            Code = "GROC",
                            CreatedDate = new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Utc).AddTicks(3311),
                            Description = "Daily household items",
                            EntityState = 0,
                            IsActive = true,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTimeOffset(new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Unspecified).AddTicks(3319), new TimeSpan(0, 0, 0, 0, 0)),
                            LastSyncedAt = new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Utc).AddTicks(3300),
                            Name = "Grocery",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Utc).AddTicks(3315),
                            Version = 0
                        },
                        new
                        {
                            Id = "5",
                            Code = "CARE",
                            CreatedDate = new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Utc).AddTicks(3340),
                            Description = "Health and hygiene products",
                            EntityState = 0,
                            IsActive = true,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTimeOffset(new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Unspecified).AddTicks(3346), new TimeSpan(0, 0, 0, 0, 0)),
                            LastSyncedAt = new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Utc).AddTicks(3336),
                            Name = "Personal Care",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Utc).AddTicks(3343),
                            Version = 0
                        },
                        new
                        {
                            Id = "6",
                            Code = "ELEC",
                            CreatedDate = new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Utc).AddTicks(3373),
                            Description = "Electronic devices and accessories",
                            EntityState = 0,
                            IsActive = true,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTimeOffset(new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Unspecified).AddTicks(3379), new TimeSpan(0, 0, 0, 0, 0)),
                            LastSyncedAt = new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Utc).AddTicks(3370),
                            Name = "Electronics",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 2, 24, 16, 1, 37, 80, DateTimeKind.Utc).AddTicks(3376),
                            Version = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
