// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMIS.Infrastructure.Mobile.Context;

#nullable disable

namespace SMIS.Infrastructure.Mobile.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20260324052312_softmig")]
    partial class softmig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SMIS.Domain.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSyncedToServer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("IsSyncedToServer");

                    b.HasIndex("LastModifiedUtc");

                    b.HasIndex("ShopId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Code = "BEV",
                            CreatedDate = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1192),
                            Description = "Drinks and beverages",
                            EntityState = "Unchanged",
                            IsActive = true,
                            IsDeleted = false,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1340),
                            LastSyncedAt = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(987),
                            Name = "Beverages",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1269),
                            Version = 0
                        },
                        new
                        {
                            Id = "2",
                            Code = "FOOD",
                            CreatedDate = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1465),
                            Description = "Edible products and snacks",
                            EntityState = "Unchanged",
                            IsActive = true,
                            IsDeleted = false,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1466),
                            LastSyncedAt = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1464),
                            Name = "Food Items",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1465),
                            Version = 0
                        },
                        new
                        {
                            Id = "3",
                            Code = "STAT",
                            CreatedDate = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1473),
                            Description = "Office and school supplies",
                            EntityState = "Unchanged",
                            IsActive = true,
                            IsDeleted = false,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1473),
                            LastSyncedAt = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1472),
                            Name = "Stationery",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1473),
                            Version = 0
                        },
                        new
                        {
                            Id = "4",
                            Code = "GROC",
                            CreatedDate = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1485),
                            Description = "Daily household items",
                            EntityState = "Unchanged",
                            IsActive = true,
                            IsDeleted = false,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1485),
                            LastSyncedAt = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1484),
                            Name = "Grocery",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1485),
                            Version = 0
                        },
                        new
                        {
                            Id = "5",
                            Code = "CARE",
                            CreatedDate = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1489),
                            Description = "Health and hygiene products",
                            EntityState = "Unchanged",
                            IsActive = true,
                            IsDeleted = false,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1490),
                            LastSyncedAt = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1489),
                            Name = "Personal Care",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1490),
                            Version = 0
                        },
                        new
                        {
                            Id = "6",
                            Code = "ELEC",
                            CreatedDate = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1495),
                            Description = "Electronic devices and accessories",
                            EntityState = "Unchanged",
                            IsActive = true,
                            IsDeleted = false,
                            IsPublic = false,
                            IsSyncedToServer = true,
                            LastModifiedUtc = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1495),
                            LastSyncedAt = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1494),
                            Name = "Electronics",
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 3, 24, 9, 53, 12, 562, DateTimeKind.Local).AddTicks(1495),
                            Version = 0
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Translation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSyncedToServer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LanguageNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationKeyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("LanguageNo");

                    b.HasIndex("TranslationKeyId", "LanguageNo")
                        .IsUnique();

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.TranslationKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSyncedToServer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("MessageCode");

                    b.ToTable("TranslationKeys");
                });

            modelBuilder.Entity("SMIS.Infrastructure.Mobile.Entities.DeletedRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiEndpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSyncedToServer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("IsSyncedToServer");

                    b.ToTable("DeletedRecords");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Translation", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Localization.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Localization.TranslationKey", "TranslationKey")
                        .WithMany("Translations")
                        .HasForeignKey("TranslationKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TranslationKey");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.TranslationKey", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
