// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMIS.Infrastructure.Context;

#nullable disable

namespace SMIS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119152635_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SMIS.Domain.Entities.AppLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Level");

                    b.HasIndex("UserId");

                    b.ToTable("AppLogs");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.District", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationKeyId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PublicId");

                    b.HasIndex("TranslationKeyId")
                        .IsUnique();

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            PublicId = "district-kabul-center-guid",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 870, DateTimeKind.Local).AddTicks(2117),
                            Id = 1,
                            IsPublic = false,
                            Name = "Kabul Center",
                            TranslationKeyId = "district_kabul_center",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 870, DateTimeKind.Local).AddTicks(2120)
                        },
                        new
                        {
                            PublicId = "district-kabul-north-guid",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 870, DateTimeKind.Local).AddTicks(2480),
                            Id = 2,
                            IsPublic = false,
                            Name = "Kabul North",
                            TranslationKeyId = "district_kabul_north",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 870, DateTimeKind.Local).AddTicks(2483)
                        },
                        new
                        {
                            PublicId = "district-herat-center-guid",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 870, DateTimeKind.Local).AddTicks(2493),
                            Id = 3,
                            IsPublic = false,
                            Name = "Herat Center",
                            TranslationKeyId = "district_herat_center",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 870, DateTimeKind.Local).AddTicks(2493)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c115599-c02c-49a0-a016-0bd4674274e3",
                            Email = "admin@local",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCAL",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEMMSO8VPFQU1um5Jf6+4hLBm9Ttr5sFwNbf6QZZOc95j3dXdKH9MbuFJWENjnDbSXw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "admin-seed",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f5d678c6-6a0c-40f4-96c8-02554c0c890e",
                            Email = "user@local",
                            EmailConfirmed = true,
                            FirstName = "Default",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@LOCAL",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEL7xJw4Awx64PkS1D2rJdNJQMLf5UNpqmLCH0rnc/3ef8uugt/iU5TXmnOeU/jD3GQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "user-seed",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "en",
                            IsActive = true,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ps",
                            IsActive = true,
                            Name = "Pashto"
                        },
                        new
                        {
                            Id = 3,
                            Code = "fa",
                            IsActive = true,
                            Name = "Farsi"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Translation", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationKeyPublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PublicId");

                    b.HasIndex("LanguageNo");

                    b.HasIndex("TranslationKeyPublicId");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            PublicId = "70f47b9b-6235-43cd-9403-fa8a19b497ab",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8081),
                            Id = 1,
                            IsPublic = false,
                            LanguageNo = 1,
                            Name = "",
                            TranslationKeyPublicId = "district_kabul_center",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8085)
                        },
                        new
                        {
                            PublicId = "70937a31-eb87-412b-af7c-01e0ef078972",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8771),
                            Id = 2,
                            IsPublic = false,
                            LanguageNo = 2,
                            Name = "",
                            TranslationKeyPublicId = "district_kabul_center",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8774)
                        },
                        new
                        {
                            PublicId = "71c75022-5237-4d52-b043-8573033d7542",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8784),
                            Id = 3,
                            IsPublic = false,
                            LanguageNo = 3,
                            Name = "",
                            TranslationKeyPublicId = "district_kabul_center",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8785)
                        },
                        new
                        {
                            PublicId = "c0e5b266-9e16-4ae1-835a-b3d02f3f94ca",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8787),
                            Id = 4,
                            IsPublic = false,
                            LanguageNo = 1,
                            Name = "",
                            TranslationKeyPublicId = "district_kabul_north",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8788)
                        },
                        new
                        {
                            PublicId = "18d0ade6-1047-4c77-bb19-a3910717fe01",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8791),
                            Id = 5,
                            IsPublic = false,
                            LanguageNo = 2,
                            Name = "",
                            TranslationKeyPublicId = "district_kabul_north",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8791)
                        },
                        new
                        {
                            PublicId = "5b0e233e-c804-417d-8575-4c2af651867e",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8821),
                            Id = 6,
                            IsPublic = false,
                            LanguageNo = 3,
                            Name = "",
                            TranslationKeyPublicId = "district_kabul_north",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8821)
                        },
                        new
                        {
                            PublicId = "311fff13-a944-4768-9e85-ea4d7a6c5825",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8824),
                            Id = 7,
                            IsPublic = false,
                            LanguageNo = 1,
                            Name = "",
                            TranslationKeyPublicId = "district_herat_center",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8824)
                        },
                        new
                        {
                            PublicId = "f08664da-f030-4d0c-bb99-c71ee1364092",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8827),
                            Id = 8,
                            IsPublic = false,
                            LanguageNo = 2,
                            Name = "",
                            TranslationKeyPublicId = "district_herat_center",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8827)
                        },
                        new
                        {
                            PublicId = "0dd05a1b-6cb0-40e4-9add-0637471cfb79",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8838),
                            Id = 9,
                            IsPublic = false,
                            LanguageNo = 3,
                            Name = "",
                            TranslationKeyPublicId = "district_herat_center",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8838)
                        },
                        new
                        {
                            PublicId = "cac3e32e-92fc-40e5-bd2b-8341a5489792",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8840),
                            Id = 10,
                            IsPublic = false,
                            LanguageNo = 1,
                            Name = "",
                            TranslationKeyPublicId = "province_kabul",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8841)
                        },
                        new
                        {
                            PublicId = "46cb7ca1-4a43-47f5-b49e-8b1daa4c4c9f",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8843),
                            Id = 11,
                            IsPublic = false,
                            LanguageNo = 2,
                            Name = "",
                            TranslationKeyPublicId = "province_kabul",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8844)
                        },
                        new
                        {
                            PublicId = "5ded76fc-9fd6-43f6-a168-4e592827699c",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8846),
                            Id = 12,
                            IsPublic = false,
                            LanguageNo = 3,
                            Name = "",
                            TranslationKeyPublicId = "province_kabul",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8846)
                        },
                        new
                        {
                            PublicId = "462fd37e-4c02-42bf-946b-799c5e22024d",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8849),
                            Id = 13,
                            IsPublic = false,
                            LanguageNo = 1,
                            Name = "",
                            TranslationKeyPublicId = "province_herat",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8849)
                        },
                        new
                        {
                            PublicId = "4b117deb-9a69-4e49-8b56-3618127edc62",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8851),
                            Id = 14,
                            IsPublic = false,
                            LanguageNo = 2,
                            Name = "",
                            TranslationKeyPublicId = "province_herat",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8852)
                        },
                        new
                        {
                            PublicId = "9f4c961e-c323-4a13-9263-f649575d1c4b",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8854),
                            Id = 15,
                            IsPublic = false,
                            LanguageNo = 3,
                            Name = "",
                            TranslationKeyPublicId = "province_herat",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(8855)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.TranslationKey", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MessageCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PublicId");

                    b.ToTable("TranslationKeys");

                    b.HasData(
                        new
                        {
                            PublicId = "district_kabul_center",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 866, DateTimeKind.Local).AddTicks(7187),
                            Id = 1,
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = 1001,
                            Name = "Kabul Center District",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 867, DateTimeKind.Local).AddTicks(9784)
                        },
                        new
                        {
                            PublicId = "district_kabul_north",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(2622),
                            Id = 2,
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = 1002,
                            Name = "Kabul North District",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(2625)
                        },
                        new
                        {
                            PublicId = "district_herat_center",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(2639),
                            Id = 3,
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = 1003,
                            Name = "Herat Center District",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(2640)
                        },
                        new
                        {
                            PublicId = "province_kabul",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(2643),
                            Id = 4,
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = 2001,
                            Name = "Kabul Province",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(2643)
                        },
                        new
                        {
                            PublicId = "province_herat",
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(2646),
                            Id = 5,
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = 2002,
                            Name = "Herat Province",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 868, DateTimeKind.Local).AddTicks(2647)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 869, DateTimeKind.Local).AddTicks(6319),
                            IsPublic = false,
                            Name = "Kabul",
                            PublicId = "09e942d8-8520-4ae1-9518-5e4ef8a1d909",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 869, DateTimeKind.Local).AddTicks(6323)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 869, DateTimeKind.Local).AddTicks(6358),
                            IsPublic = false,
                            Name = "Herat",
                            PublicId = "4f23fe62-2e17-452b-8abc-36664ccc9d08",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 869, DateTimeKind.Local).AddTicks(6359)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 869, DateTimeKind.Local).AddTicks(6362),
                            IsPublic = false,
                            Name = "Kandahar",
                            PublicId = "6bce773d-28b3-4349-8739-2714fa8ef291",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 869, DateTimeKind.Local).AddTicks(6362)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 869, DateTimeKind.Local).AddTicks(6365),
                            IsPublic = false,
                            Name = "Balkh",
                            PublicId = "973f4757-7d32-499a-9e2c-cb7685bc5c18",
                            UpdatedDate = new DateTime(2026, 1, 19, 19, 56, 33, 869, DateTimeKind.Local).AddTicks(6365)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.ProvinceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProvinceId", "LanguageId")
                        .IsUnique();

                    b.ToTable("ProvinceTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Kabul",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "کابل",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "کابل",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Herat",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "هرات",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 6,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "هرات",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Kandahar",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 8,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "کندهار",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 9,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "قندهار",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 10,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Balkh",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 11,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "بلخ",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 12,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "بلخ",
                            ProvinceId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMIS.Domain.Entities.District", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Localization.TranslationKey", "TranslationKey")
                        .WithOne()
                        .HasForeignKey("SMIS.Domain.Entities.District", "TranslationKeyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TranslationKey");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Translation", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Localization.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Localization.TranslationKey", "TranslationKey")
                        .WithMany("Translations")
                        .HasForeignKey("TranslationKeyPublicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TranslationKey");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.ProvinceTranslation", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Localization.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Province", "Province")
                        .WithMany("Translations")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.TranslationKey", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Province", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
