// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMIS.Infrastructure.Context;

#nullable disable

namespace SMIS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119115446_addTranlation")]
    partial class addTranlation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SMIS.Domain.Entities.AppLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Level");

                    b.HasIndex("UserId");

                    b.ToTable("AppLogs");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.District", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationKeyId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PublicId");

                    b.HasIndex("TranslationKeyId")
                        .IsUnique();

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1669a354-ca9b-4ac4-ba85-e1b58da9c06e",
                            Email = "admin@local",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCAL",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEFQmfWMWAYvwfYIG63T8m7VdO+eUfokmL/Drdw2C8XZVr7xRKRGQylea8XhVUPz4bw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "admin-seed",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57b54246-52f5-4f24-a823-e6826cf06657",
                            Email = "user@local",
                            EmailConfirmed = true,
                            FirstName = "Default",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@LOCAL",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEEyJaIgrAWbiJCd2gIRQ/rNzPfAXF2BC+HFI5ZRY5lBsuNQmqkxtrEhm85etSxJWXQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "user-seed",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "en",
                            IsActive = true,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ps",
                            IsActive = true,
                            Name = "Pashto"
                        },
                        new
                        {
                            Id = 3,
                            Code = "fa",
                            IsActive = true,
                            Name = "Farsi"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Translation", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationKeyPublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PublicId");

                    b.HasIndex("LanguageNo");

                    b.HasIndex("TranslationKeyPublicId");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.TranslationKey", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MessageCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PublicId");

                    b.ToTable("TranslationKeys");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 19, 16, 24, 45, 806, DateTimeKind.Local).AddTicks(1384),
                            IsPublic = false,
                            Name = "Kabul",
                            PublicId = "57997926-b268-4c70-a48f-372a2f7a98df",
                            UpdatedDate = new DateTime(2026, 1, 19, 16, 24, 45, 807, DateTimeKind.Local).AddTicks(4995)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 19, 16, 24, 45, 807, DateTimeKind.Local).AddTicks(6881),
                            IsPublic = false,
                            Name = "Herat",
                            PublicId = "52f264c1-eb97-478c-a604-8d772dd45ca4",
                            UpdatedDate = new DateTime(2026, 1, 19, 16, 24, 45, 807, DateTimeKind.Local).AddTicks(6884)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 19, 16, 24, 45, 807, DateTimeKind.Local).AddTicks(6905),
                            IsPublic = false,
                            Name = "Kandahar",
                            PublicId = "0bdfac84-703b-45a7-9d19-ff215b2c34eb",
                            UpdatedDate = new DateTime(2026, 1, 19, 16, 24, 45, 807, DateTimeKind.Local).AddTicks(6906)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 19, 16, 24, 45, 807, DateTimeKind.Local).AddTicks(6914),
                            IsPublic = false,
                            Name = "Balkh",
                            PublicId = "1e996013-eee4-40b2-933a-1e8bc3815495",
                            UpdatedDate = new DateTime(2026, 1, 19, 16, 24, 45, 807, DateTimeKind.Local).AddTicks(6915)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.ProvinceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProvinceId", "LanguageId")
                        .IsUnique();

                    b.ToTable("ProvinceTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Kabul",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "کابل",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "کابل",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Herat",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "هرات",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 6,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "هرات",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Kandahar",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 8,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "کندهار",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 9,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "قندهار",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 10,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Balkh",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 11,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "بلخ",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 12,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "بلخ",
                            ProvinceId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMIS.Domain.Entities.District", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Localization.TranslationKey", "TranslationKey")
                        .WithOne()
                        .HasForeignKey("SMIS.Domain.Entities.District", "TranslationKeyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TranslationKey");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Translation", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Localization.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Localization.TranslationKey", "TranslationKey")
                        .WithMany("Translations")
                        .HasForeignKey("TranslationKeyPublicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TranslationKey");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.ProvinceTranslation", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Localization.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Province", "Province")
                        .WithMany("Translations")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.TranslationKey", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Province", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
