// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMIS.Infrastructure.Context;

#nullable disable

namespace SMIS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260121090115_AddDbSeedeFroShopsdfd")]
    partial class AddDbSeedeFroShopsdfd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SMIS.Domain.Entities.AppLog", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PublicId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Level");

                    b.HasIndex("UserId");

                    b.ToTable("AppLogs");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.District", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationKeyId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PublicId");

                    b.HasIndex("TranslationKeyId")
                        .IsUnique();

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            PublicId = "1",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 434, DateTimeKind.Local).AddTicks(1282),
                            Id = 1,
                            IsPublic = false,
                            Name = "Kabul Center",
                            TranslationKeyId = "1",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 434, DateTimeKind.Local).AddTicks(1284)
                        },
                        new
                        {
                            PublicId = "2",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 434, DateTimeKind.Local).AddTicks(1389),
                            Id = 2,
                            IsPublic = false,
                            Name = "Kabul North",
                            TranslationKeyId = "2",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 434, DateTimeKind.Local).AddTicks(1389)
                        },
                        new
                        {
                            PublicId = "3",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 434, DateTimeKind.Local).AddTicks(1391),
                            Id = 3,
                            IsPublic = false,
                            Name = "Herat Center",
                            TranslationKeyId = "3",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 434, DateTimeKind.Local).AddTicks(1391)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b2ae8189-c5b6-4ac3-aec5-8e31fd23bad3",
                            Email = "admin@local",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCAL",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEA7dvSyo+IJdYQ2H/3uaTWlb2lBfi2atkasFofnzE32AYmrQSOOeCDrmvjsnrh1K+A==",
                            PhoneNumberConfirmed = false,
                            PublicId = "1",
                            SecurityStamp = "admin-seed",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dfc8f85d-5431-45f0-861d-403e565a5873",
                            Email = "user@local",
                            EmailConfirmed = true,
                            FirstName = "Default",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@LOCAL",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEBLjtzNNTzhMiONQiQshpAP5rddRmGiCoR7/7WexkjlVBnT7rplwVleR/YleM2cibg==",
                            PhoneNumberConfirmed = false,
                            PublicId = "2",
                            SecurityStamp = "user-seed",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Language", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PublicId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            PublicId = "1",
                            Code = "en",
                            Id = 1,
                            IsActive = true,
                            Name = "English"
                        },
                        new
                        {
                            PublicId = "2",
                            Code = "ps",
                            Id = 2,
                            IsActive = true,
                            Name = "Pashto"
                        },
                        new
                        {
                            PublicId = "3",
                            Code = "fa",
                            Id = 3,
                            IsActive = true,
                            Name = "Farsi"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Translation", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationKeyPublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PublicId");

                    b.HasIndex("LanguageNo");

                    b.HasIndex("TranslationKeyPublicId");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            PublicId = "1",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(5803),
                            Id = 1,
                            IsPublic = false,
                            LanguageNo = 1,
                            Name = "",
                            TranslationKeyPublicId = "1",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(5804)
                        },
                        new
                        {
                            PublicId = "2",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6024),
                            Id = 2,
                            IsPublic = false,
                            LanguageNo = 2,
                            Name = "",
                            TranslationKeyPublicId = "1",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6024)
                        },
                        new
                        {
                            PublicId = "3",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6025),
                            Id = 3,
                            IsPublic = false,
                            LanguageNo = 3,
                            Name = "",
                            TranslationKeyPublicId = "1",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6026)
                        },
                        new
                        {
                            PublicId = "4",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6027),
                            Id = 4,
                            IsPublic = false,
                            LanguageNo = 1,
                            Name = "",
                            TranslationKeyPublicId = "2",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6027)
                        },
                        new
                        {
                            PublicId = "5",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6028),
                            Id = 5,
                            IsPublic = false,
                            LanguageNo = 2,
                            Name = "",
                            TranslationKeyPublicId = "2",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6028)
                        },
                        new
                        {
                            PublicId = "6",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6029),
                            Id = 6,
                            IsPublic = false,
                            LanguageNo = 3,
                            Name = "",
                            TranslationKeyPublicId = "2",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6029)
                        },
                        new
                        {
                            PublicId = "7",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6030),
                            Id = 7,
                            IsPublic = false,
                            LanguageNo = 1,
                            Name = "",
                            TranslationKeyPublicId = "3",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6030)
                        },
                        new
                        {
                            PublicId = "8",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6031),
                            Id = 8,
                            IsPublic = false,
                            LanguageNo = 2,
                            Name = "",
                            TranslationKeyPublicId = "3",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6032)
                        },
                        new
                        {
                            PublicId = "9",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6032),
                            Id = 9,
                            IsPublic = false,
                            LanguageNo = 3,
                            Name = "",
                            TranslationKeyPublicId = "3",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6033)
                        },
                        new
                        {
                            PublicId = "10",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6034),
                            Id = 10,
                            IsPublic = false,
                            LanguageNo = 1,
                            Name = "",
                            TranslationKeyPublicId = "4",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6034)
                        },
                        new
                        {
                            PublicId = "11",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6035),
                            Id = 11,
                            IsPublic = false,
                            LanguageNo = 2,
                            Name = "",
                            TranslationKeyPublicId = "4",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6035)
                        },
                        new
                        {
                            PublicId = "12",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6036),
                            Id = 12,
                            IsPublic = false,
                            LanguageNo = 3,
                            Name = "",
                            TranslationKeyPublicId = "4",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6037)
                        },
                        new
                        {
                            PublicId = "13",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6037),
                            Id = 13,
                            IsPublic = false,
                            LanguageNo = 1,
                            Name = "",
                            TranslationKeyPublicId = "5",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6038)
                        },
                        new
                        {
                            PublicId = "14",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6039),
                            Id = 14,
                            IsPublic = false,
                            LanguageNo = 2,
                            Name = "",
                            TranslationKeyPublicId = "5",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6039)
                        },
                        new
                        {
                            PublicId = "15",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6040),
                            Id = 15,
                            IsPublic = false,
                            LanguageNo = 3,
                            Name = "",
                            TranslationKeyPublicId = "5",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(6040)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.TranslationKey", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PublicId");

                    b.HasIndex("MessageCode");

                    b.ToTable("TranslationKeys");

                    b.HasData(
                        new
                        {
                            PublicId = "1",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 432, DateTimeKind.Local).AddTicks(5061),
                            Id = 1,
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = "1001",
                            Name = "Kabul Center District",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(1911)
                        },
                        new
                        {
                            PublicId = "2",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(3076),
                            Id = 2,
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = "1002",
                            Name = "Kabul North District",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(3077)
                        },
                        new
                        {
                            PublicId = "3",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(3079),
                            Id = 3,
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = "1003",
                            Name = "Herat Center District",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(3079)
                        },
                        new
                        {
                            PublicId = "4",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(3080),
                            Id = 4,
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = "2001",
                            Name = "Kabul Province",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(3081)
                        },
                        new
                        {
                            PublicId = "5",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(3082),
                            Id = 5,
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = "2002",
                            Name = "Herat Province",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(3082)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Province", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PublicId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            PublicId = "1",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(9289),
                            Id = 1,
                            IsPublic = false,
                            Name = "Kabul",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(9289)
                        },
                        new
                        {
                            PublicId = "2",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(9292),
                            Id = 2,
                            IsPublic = false,
                            Name = "Herat",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(9292)
                        },
                        new
                        {
                            PublicId = "3",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(9293),
                            Id = 3,
                            IsPublic = false,
                            Name = "Kandahar",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(9293)
                        },
                        new
                        {
                            PublicId = "4",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(9294),
                            Id = 4,
                            IsPublic = false,
                            Name = "Balkh",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 433, DateTimeKind.Local).AddTicks(9295)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.ProvinceTranslation", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PublicId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProvinceId", "LanguageId")
                        .IsUnique();

                    b.ToTable("ProvinceTranslations");

                    b.HasData(
                        new
                        {
                            PublicId = "1",
                            Id = 1,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Kabul",
                            ProvinceId = 1
                        },
                        new
                        {
                            PublicId = "2",
                            Id = 2,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "کابل",
                            ProvinceId = 1
                        },
                        new
                        {
                            PublicId = "3",
                            Id = 3,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "کابل",
                            ProvinceId = 1
                        },
                        new
                        {
                            PublicId = "4",
                            Id = 4,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Herat",
                            ProvinceId = 2
                        },
                        new
                        {
                            PublicId = "5",
                            Id = 5,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "هرات",
                            ProvinceId = 2
                        },
                        new
                        {
                            PublicId = "6",
                            Id = 6,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "هرات",
                            ProvinceId = 2
                        },
                        new
                        {
                            PublicId = "7",
                            Id = 7,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Kandahar",
                            ProvinceId = 3
                        },
                        new
                        {
                            PublicId = "8",
                            Id = 8,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "کندهار",
                            ProvinceId = 3
                        },
                        new
                        {
                            PublicId = "9",
                            Id = 9,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "قندهار",
                            ProvinceId = 3
                        },
                        new
                        {
                            PublicId = "10",
                            Id = 10,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Balkh",
                            ProvinceId = 4
                        },
                        new
                        {
                            PublicId = "11",
                            Id = 11,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "بلخ",
                            ProvinceId = 4
                        },
                        new
                        {
                            PublicId = "12",
                            Id = 12,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "بلخ",
                            ProvinceId = 4
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Shop", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShopType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PublicId");

                    b.ToTable("Shops", (string)null);

                    b.HasData(
                        new
                        {
                            PublicId = "1",
                            Address = "Kabul Center",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 434, DateTimeKind.Local).AddTicks(3843),
                            Email = "main@pharmacy.local",
                            Id = 1,
                            IsActive = true,
                            IsPublic = false,
                            Name = "Main Pharmacy",
                            PhoneNumber = "0700000001",
                            ShopType = 1,
                            TaxNumber = "TAX001",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 434, DateTimeKind.Local).AddTicks(3844)
                        },
                        new
                        {
                            PublicId = "2",
                            Address = "Herat Center",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 434, DateTimeKind.Local).AddTicks(4373),
                            Email = "city@pharmacy.local",
                            Id = 2,
                            IsActive = true,
                            IsPublic = false,
                            Name = "City Pharmacy",
                            PhoneNumber = "0700000002",
                            ShopType = 2,
                            TaxNumber = "TAX002",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 434, DateTimeKind.Local).AddTicks(4373)
                        },
                        new
                        {
                            PublicId = "3",
                            Address = "Kandahar Center",
                            CreatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 434, DateTimeKind.Local).AddTicks(4375),
                            Email = "health@store.local",
                            Id = 3,
                            IsActive = true,
                            IsPublic = false,
                            Name = "Health Store",
                            PhoneNumber = "0700000003",
                            ShopType = 1,
                            TaxNumber = "TAX003",
                            UpdatedDate = new DateTime(2026, 1, 21, 13, 31, 15, 434, DateTimeKind.Local).AddTicks(4376)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("PublicId");

                    b.ToTable("UnitOfMeasure", (string)null);

                    b.HasData(
                        new
                        {
                            PublicId = "1",
                            Id = 1,
                            Name = "Piece",
                            Symbol = "pcs"
                        },
                        new
                        {
                            PublicId = "2",
                            Id = 2,
                            Name = "Gram",
                            Symbol = "g"
                        },
                        new
                        {
                            PublicId = "3",
                            Id = 3,
                            Name = "Milliliter",
                            Symbol = "ml"
                        },
                        new
                        {
                            PublicId = "4",
                            Id = 4,
                            Name = "Box",
                            Symbol = "box"
                        },
                        new
                        {
                            PublicId = "5",
                            Id = 5,
                            Name = "Bottle",
                            Symbol = "btl"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMIS.Domain.Entities.District", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Localization.TranslationKey", "TranslationKey")
                        .WithOne()
                        .HasForeignKey("SMIS.Domain.Entities.District", "TranslationKeyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TranslationKey");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Translation", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Localization.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageNo")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Localization.TranslationKey", "TranslationKey")
                        .WithMany("Translations")
                        .HasForeignKey("TranslationKeyPublicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TranslationKey");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.ProvinceTranslation", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Localization.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Province", "Province")
                        .WithMany("Translations")
                        .HasForeignKey("ProvinceId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.TranslationKey", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Province", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
