// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMIS.Infrastructure.Context;

#nullable disable

namespace SMIS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SMIS.Domain.Entities.AppLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Level");

                    b.HasIndex("UserId");

                    b.ToTable("AppLogs", (string)null);
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Code = "BEV",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 729, DateTimeKind.Local).AddTicks(2583),
                            Description = "Drinks and beverages",
                            IsActive = true,
                            IsPublic = false,
                            Name = "Beverages",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 729, DateTimeKind.Local).AddTicks(2594)
                        },
                        new
                        {
                            Id = "2",
                            Code = "SOFT",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 729, DateTimeKind.Local).AddTicks(4916),
                            Description = "Carbonated and non-carbonated drinks",
                            IsActive = true,
                            IsPublic = false,
                            Name = "Soft Drinks",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 729, DateTimeKind.Local).AddTicks(4924)
                        },
                        new
                        {
                            Id = "3",
                            Code = "FOOD",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 729, DateTimeKind.Local).AddTicks(4931),
                            Description = "Edible products",
                            IsActive = true,
                            IsPublic = false,
                            Name = "Food Items",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 729, DateTimeKind.Local).AddTicks(4933)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "11ccf456-d270-472b-89e0-38d26c0305d7",
                            Email = "admin@local",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCAL",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEFvqRn2KCmjYvMDdZ1ubID5Zgb8/eGQmUVxI7fVF51FFwhE3yQk726Ehqb6QuMjlAg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "admin-seed",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "68c05f9c-6cb6-4948-9732-91c6032fc72d",
                            Email = "user@local",
                            EmailConfirmed = true,
                            FirstName = "Default",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@LOCAL",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEAb1FV00CELiQcmlhCs4qFO7RQyLaYehn8T0Rf4elXtzAUoHRDRY+eVFoQDDGoup2A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "user-seed",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Code = "en",
                            IsActive = true,
                            Name = "English"
                        },
                        new
                        {
                            Id = "2",
                            Code = "ps",
                            IsActive = true,
                            Name = "Pashto"
                        },
                        new
                        {
                            Id = "3",
                            Code = "fa",
                            IsActive = true,
                            Name = "Farsi"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Translation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationKeyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageNo");

                    b.HasIndex("TranslationKeyId", "LanguageNo")
                        .IsUnique();

                    b.ToTable("Translations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 720, DateTimeKind.Local).AddTicks(1881),
                            IsPublic = false,
                            LanguageNo = "1",
                            Name = "Kabul Center District",
                            TranslationKeyId = "1",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 720, DateTimeKind.Local).AddTicks(1889)
                        },
                        new
                        {
                            Id = "2",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1763),
                            IsPublic = false,
                            LanguageNo = "2",
                            Name = "منطقه مرکز کابل",
                            TranslationKeyId = "1",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1778)
                        },
                        new
                        {
                            Id = "3",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1789),
                            IsPublic = false,
                            LanguageNo = "1",
                            Name = "Kabul North District",
                            TranslationKeyId = "2",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1790)
                        },
                        new
                        {
                            Id = "4",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1792),
                            IsPublic = false,
                            LanguageNo = "2",
                            Name = "منطقه شمال کابل",
                            TranslationKeyId = "2",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1793)
                        },
                        new
                        {
                            Id = "5",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1795),
                            IsPublic = false,
                            LanguageNo = "1",
                            Name = "Herat Center District",
                            TranslationKeyId = "3",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1795)
                        },
                        new
                        {
                            Id = "6",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1797),
                            IsPublic = false,
                            LanguageNo = "2",
                            Name = "منطقه مرکز هرات",
                            TranslationKeyId = "3",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1797)
                        },
                        new
                        {
                            Id = "7",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1799),
                            IsPublic = false,
                            LanguageNo = "1",
                            Name = "Kabul Province",
                            TranslationKeyId = "4",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1815)
                        },
                        new
                        {
                            Id = "8",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1818),
                            IsPublic = false,
                            LanguageNo = "2",
                            Name = "ولایت کابل",
                            TranslationKeyId = "4",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1818)
                        },
                        new
                        {
                            Id = "9",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1820),
                            IsPublic = false,
                            LanguageNo = "1",
                            Name = "Herat Province",
                            TranslationKeyId = "5",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1821)
                        },
                        new
                        {
                            Id = "10",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1823),
                            IsPublic = false,
                            LanguageNo = "2",
                            Name = "ولایت هرات",
                            TranslationKeyId = "5",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1823)
                        },
                        new
                        {
                            Id = "11",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1825),
                            IsPublic = false,
                            LanguageNo = "1",
                            Name = "Welcome Message",
                            TranslationKeyId = "6",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1826)
                        },
                        new
                        {
                            Id = "12",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1828),
                            IsPublic = false,
                            LanguageNo = "2",
                            Name = "پیام خوش آمدید",
                            TranslationKeyId = "6",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 721, DateTimeKind.Local).AddTicks(1829)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.TranslationKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageCode");

                    b.ToTable("TranslationKeys", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 716, DateTimeKind.Local).AddTicks(2632),
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = "1001",
                            Name = "Kabul Center District",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 718, DateTimeKind.Local).AddTicks(6913)
                        },
                        new
                        {
                            Id = "2",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 719, DateTimeKind.Local).AddTicks(2208),
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = "1002",
                            Name = "Kabul North District",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 719, DateTimeKind.Local).AddTicks(2221)
                        },
                        new
                        {
                            Id = "3",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 719, DateTimeKind.Local).AddTicks(2236),
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = "1003",
                            Name = "Herat Center District",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 719, DateTimeKind.Local).AddTicks(2236)
                        },
                        new
                        {
                            Id = "4",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 719, DateTimeKind.Local).AddTicks(2241),
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = "2001",
                            Name = "Kabul Province",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 719, DateTimeKind.Local).AddTicks(2241)
                        },
                        new
                        {
                            Id = "5",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 719, DateTimeKind.Local).AddTicks(2244),
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = "2002",
                            Name = "Herat Province",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 719, DateTimeKind.Local).AddTicks(2244)
                        },
                        new
                        {
                            Id = "6",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 719, DateTimeKind.Local).AddTicks(2246),
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = "3001",
                            Name = "Welcome Message",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 719, DateTimeKind.Local).AddTicks(2246)
                        },
                        new
                        {
                            Id = "7",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 719, DateTimeKind.Local).AddTicks(2249),
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = "3002",
                            Name = "Error Message",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 719, DateTimeKind.Local).AddTicks(2249)
                        },
                        new
                        {
                            Id = "8",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 719, DateTimeKind.Local).AddTicks(2251),
                            IsActive = true,
                            IsPublic = false,
                            MessageCode = "3003",
                            Name = "Success Message",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 719, DateTimeKind.Local).AddTicks(2252)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.LocationEntities.District", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationKeyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TranslationKeyId")
                        .IsUnique();

                    b.ToTable("Districts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 723, DateTimeKind.Local).AddTicks(7019),
                            IsPublic = false,
                            Name = "Kabul Center",
                            TranslationKeyId = "1",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 723, DateTimeKind.Local).AddTicks(7032)
                        },
                        new
                        {
                            Id = "2",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 723, DateTimeKind.Local).AddTicks(7547),
                            IsPublic = false,
                            Name = "Kabul North",
                            TranslationKeyId = "2",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 723, DateTimeKind.Local).AddTicks(7549)
                        },
                        new
                        {
                            Id = "3",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 723, DateTimeKind.Local).AddTicks(7553),
                            IsPublic = false,
                            Name = "Herat Center",
                            TranslationKeyId = "3",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 723, DateTimeKind.Local).AddTicks(7553)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.LocationEntities.Province", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Provinces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 722, DateTimeKind.Local).AddTicks(7931),
                            IsPublic = false,
                            Name = "Kabul",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 722, DateTimeKind.Local).AddTicks(7948)
                        },
                        new
                        {
                            Id = "2",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 722, DateTimeKind.Local).AddTicks(7963),
                            IsPublic = false,
                            Name = "Herat",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 722, DateTimeKind.Local).AddTicks(7965)
                        },
                        new
                        {
                            Id = "3",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 722, DateTimeKind.Local).AddTicks(7970),
                            IsPublic = false,
                            Name = "Kandahar",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 722, DateTimeKind.Local).AddTicks(7972)
                        },
                        new
                        {
                            Id = "4",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 722, DateTimeKind.Local).AddTicks(7976),
                            IsPublic = false,
                            Name = "Balkh",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 722, DateTimeKind.Local).AddTicks(7978)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.LocationEntities.ProvinceTranslation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvinceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProvinceId", "LanguageId")
                        .IsUnique();

                    b.ToTable("ProvinceTranslations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = "1",
                            Name = "Kabul",
                            ProvinceId = "1"
                        },
                        new
                        {
                            Id = "2",
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = "2",
                            Name = "کابل",
                            ProvinceId = "1"
                        },
                        new
                        {
                            Id = "3",
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = "3",
                            Name = "کابل",
                            ProvinceId = "1"
                        },
                        new
                        {
                            Id = "4",
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = "1",
                            Name = "Herat",
                            ProvinceId = "2"
                        },
                        new
                        {
                            Id = "5",
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = "2",
                            Name = "هرات",
                            ProvinceId = "2"
                        },
                        new
                        {
                            Id = "6",
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = "3",
                            Name = "هرات",
                            ProvinceId = "2"
                        },
                        new
                        {
                            Id = "7",
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = "1",
                            Name = "Kandahar",
                            ProvinceId = "3"
                        },
                        new
                        {
                            Id = "8",
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = "2",
                            Name = "کندهار",
                            ProvinceId = "3"
                        },
                        new
                        {
                            Id = "9",
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = "3",
                            Name = "قندهار",
                            ProvinceId = "3"
                        },
                        new
                        {
                            Id = "10",
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = "1",
                            Name = "Balkh",
                            ProvinceId = "4"
                        },
                        new
                        {
                            Id = "11",
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = "2",
                            Name = "بلخ",
                            ProvinceId = "4"
                        },
                        new
                        {
                            Id = "12",
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = "3",
                            Name = "بلخ",
                            ProvinceId = "4"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUnitId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SalePricePerBaseUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShopId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Barcode = "1234567890123",
                            BaseUnitId = "1",
                            CategoryId = "1",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 727, DateTimeKind.Local).AddTicks(4254),
                            Description = "Pain reliever",
                            ImageUrl = "https://example.com/images/paracetamol.jpg",
                            IsActive = true,
                            IsPublic = false,
                            Name = "Paracetamol 500mg",
                            SKU = "PAR-500MG-001",
                            SalePricePerBaseUnit = 50,
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 727, DateTimeKind.Local).AddTicks(4271)
                        },
                        new
                        {
                            Id = "2",
                            Barcode = "1234567890124",
                            BaseUnitId = "1",
                            CategoryId = "1",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 728, DateTimeKind.Local).AddTicks(5873),
                            Description = "Anti-inflammatory",
                            ImageUrl = "https://example.com/images/ibuprofen.jpg",
                            IsActive = true,
                            IsPublic = false,
                            Name = "Ibuprofen 200mg",
                            SKU = "IBU-200MG-002",
                            SalePricePerBaseUnit = 30,
                            ShopId = "1",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 728, DateTimeKind.Local).AddTicks(5886)
                        },
                        new
                        {
                            Id = "3",
                            Barcode = "1234567890125",
                            BaseUnitId = "1",
                            CategoryId = "2",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 728, DateTimeKind.Local).AddTicks(5910),
                            Description = "Blood thinner",
                            ImageUrl = "https://example.com/images/aspirin.jpg",
                            IsActive = true,
                            IsPublic = false,
                            Name = "Aspirin 100mg",
                            SKU = "ASP-100MG-003",
                            SalePricePerBaseUnit = 20,
                            ShopId = "2",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 728, DateTimeKind.Local).AddTicks(5910)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.ProductUnit", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasureId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("ProductUnit", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConversionFactor = 10m,
                            ProductId = "1",
                            UnitOfMeasureId = "1"
                        },
                        new
                        {
                            Id = "2",
                            ConversionFactor = 100m,
                            ProductId = "1",
                            UnitOfMeasureId = "2"
                        },
                        new
                        {
                            Id = "3",
                            ConversionFactor = 12m,
                            ProductId = "2",
                            UnitOfMeasureId = "1"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Shop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shop", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Address = "Kabul Center",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 725, DateTimeKind.Local).AddTicks(6626),
                            Email = "main@pharmacy.local",
                            IsActive = true,
                            IsPublic = false,
                            Name = "Main Pharmacy",
                            PhoneNumber = "0700000001",
                            ShopType = "RetailShop",
                            TaxNumber = "TAX001",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 725, DateTimeKind.Local).AddTicks(6638)
                        },
                        new
                        {
                            Id = "2",
                            Address = "Herat Center",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 726, DateTimeKind.Local).AddTicks(185),
                            Email = "city@pharmacy.local",
                            IsActive = true,
                            IsPublic = false,
                            Name = "City Pharmacy",
                            PhoneNumber = "0700000002",
                            ShopType = "WholesaleShop",
                            TaxNumber = "TAX002",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 726, DateTimeKind.Local).AddTicks(192)
                        },
                        new
                        {
                            Id = "3",
                            Address = "Kandahar Center",
                            CreatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 726, DateTimeKind.Local).AddTicks(205),
                            Email = "health@store.local",
                            IsActive = true,
                            IsPublic = false,
                            Name = "Health Store",
                            PhoneNumber = "0700000003",
                            ShopType = "RetailShop",
                            TaxNumber = "TAX003",
                            UpdatedDate = new DateTime(2026, 1, 22, 20, 50, 52, 726, DateTimeKind.Local).AddTicks(207)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasure", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Piece",
                            Symbol = "pcs"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Gram",
                            Symbol = "g"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Milliliter",
                            Symbol = "ml"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Box",
                            Symbol = "box"
                        },
                        new
                        {
                            Id = "5",
                            Name = "Bottle",
                            Symbol = "btl"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Translation", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Localization.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Localization.TranslationKey", "TranslationKey")
                        .WithMany("Translations")
                        .HasForeignKey("TranslationKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TranslationKey");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.LocationEntities.District", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Localization.TranslationKey", "TranslationKey")
                        .WithOne()
                        .HasForeignKey("SMIS.Domain.Entities.LocationEntities.District", "TranslationKeyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TranslationKey");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.LocationEntities.ProvinceTranslation", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Localization.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.LocationEntities.Province", "Province")
                        .WithMany("Translations")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Product", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SMIS.Domain.Entities.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Shop");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.ProductUnit", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Product", "Product")
                        .WithMany("ProductUnits")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("ProductUnits")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.TranslationKey", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.LocationEntities.Province", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductUnits");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Navigation("ProductUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
