// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMIS.Infrastructure.Context;

#nullable disable

namespace SMIS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AvailableBeds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmergencyBeds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EmergencyServices")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EstablishedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasLaboratory")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasOperationTheater")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasPharmacy")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasRadiology")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IcuBeds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxIdentificationNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalBeds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "100 Main St",
                            City = "Springfield",
                            Code = "H-CENTRAL",
                            Country = "US",
                            CreatedDate = new DateTime(2026, 1, 6, 15, 22, 41, 195, DateTimeKind.Local).AddTicks(1372),
                            Email = "central@example.com",
                            HospitalId = 0,
                            IsActive = true,
                            IsPublic = false,
                            Name = "Central Hospital",
                            Phone = "+1-555-0001",
                            PublicId = "a4ec3c8d-2b05-4a3d-9b08-8c6f0d1b4a11",
                            UpdatedDate = new DateTime(2026, 1, 6, 15, 22, 41, 195, DateTimeKind.Local).AddTicks(1386)
                        },
                        new
                        {
                            Id = 2,
                            Address = "200 West Ave",
                            City = "Springfield",
                            Code = "H-WEST",
                            Country = "US",
                            CreatedDate = new DateTime(2026, 1, 6, 15, 22, 41, 195, DateTimeKind.Local).AddTicks(1394),
                            Email = "west@example.com",
                            HospitalId = 0,
                            IsActive = true,
                            IsPublic = false,
                            Name = "Westside Clinic",
                            Phone = "+1-555-0002",
                            PublicId = "b8b2a2b3-6f02-4c8e-9b47-84a118e8f2c2",
                            UpdatedDate = new DateTime(2026, 1, 6, 15, 22, 41, 195, DateTimeKind.Local).AddTicks(1395)
                        },
                        new
                        {
                            Id = 3,
                            Address = "300 East Blvd",
                            City = "Springfield",
                            Code = "H-EAST",
                            Country = "US",
                            CreatedDate = new DateTime(2026, 1, 6, 15, 22, 41, 195, DateTimeKind.Local).AddTicks(1399),
                            Email = "east@example.com",
                            HospitalId = 0,
                            IsActive = true,
                            IsPublic = false,
                            Name = "East Medical Center",
                            Phone = "+1-555-0003",
                            PublicId = "c3f4d6e7-8a90-4b2c-b3d4-e5f6a7b8c9d0",
                            UpdatedDate = new DateTime(2026, 1, 6, 15, 22, 41, 195, DateTimeKind.Local).AddTicks(1400)
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<int>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "381a56f0-77ac-4bce-911f-e17e584ec9fc",
                            Email = "admin@local",
                            EmailConfirmed = true,
                            FirstName = "System",
                            HospitalId = 1,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCAL",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEFbK/9RjsWhtuP1/QTGSp/6e1ys3GVn6dpbkMZz062pJq47zYs9XXhFWM7PdBNPNQQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "admin-seed",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8457ac1f-a946-4421-b000-4b6a37be37bf",
                            Email = "user@local",
                            EmailConfirmed = true,
                            FirstName = "Default",
                            HospitalId = 1,
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@LOCAL",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxBG7PtnTzv0IuJN39seyotdu+u/prNNtAGKEA9oxBSIk8259hXw/0ZVvjXVmgJDQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "user-seed",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Laboratory.LabTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabTestGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalRange")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasurment")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LabTestGroupId");

                    b.ToTable("LabTests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "FBS",
                            Description = "Fasting blood glucose",
                            HospitalId = 0,
                            IsActive = true,
                            IsPublic = false,
                            LabTestGroupId = 1,
                            Name = "Glucose",
                            NormalRange = "70-99",
                            Price = 10,
                            PublicId = "232324e3-04af-4f37-8056-add21c0c01fb",
                            UnitOfMeasurment = "mg/dL"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "LP",
                            Description = "Total Cholesterol, HDL, LDL, Triglycerides",
                            HospitalId = 0,
                            IsActive = true,
                            IsPublic = false,
                            LabTestGroupId = 1,
                            Name = "Lipid Profile",
                            NormalRange = "Varies",
                            Price = 25,
                            PublicId = "addecc6d-b6d2-4c8d-be86-d0e9cce1427c",
                            UnitOfMeasurment = "mg/dL"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "CBC",
                            Description = "Complete Blood Count",
                            HospitalId = 0,
                            IsActive = true,
                            IsPublic = false,
                            LabTestGroupId = 2,
                            Name = "CBC",
                            NormalRange = "Varies",
                            Price = 20,
                            PublicId = "4dabb21a-f60b-44fb-b258-1cc9b6ec98b8"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "UC",
                            Description = "Microbiology culture",
                            HospitalId = 0,
                            IsActive = true,
                            IsPublic = false,
                            LabTestGroupId = 3,
                            Name = "Urine Culture",
                            NormalRange = "Negative",
                            Price = 30,
                            PublicId = "b06ed9e0-1415-49b8-8eff-da21a50725fd"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Laboratory.LabTestGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short?>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LabTestGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Chemistry tests",
                            HospitalId = 0,
                            IsPublic = false,
                            Name = "Chemistry",
                            PublicId = "ec00ec5d-fbf3-4335-8509-5b4ac80b37d6",
                            SortOrder = (short)1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Blood tests",
                            HospitalId = 0,
                            IsPublic = false,
                            Name = "Hematology",
                            PublicId = "e63814ca-a52f-40ca-8997-4b0a050499e0",
                            SortOrder = (short)2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Microbiology tests",
                            HospitalId = 0,
                            IsPublic = false,
                            Name = "Microbiology",
                            PublicId = "1d73f9d6-77a0-41fb-bffd-4173464bd4d5",
                            SortOrder = (short)3
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Localization.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "en",
                            IsActive = true,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ps",
                            IsActive = true,
                            Name = "Pashto"
                        },
                        new
                        {
                            Id = 3,
                            Code = "fa",
                            IsActive = true,
                            Name = "Farsi"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Patients.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Springfield",
                            DateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            Gender = "Male",
                            HospitalId = 1,
                            IsPublic = false,
                            LastName = "Doe",
                            Name = "John",
                            PhoneNumber = "555-1234",
                            PublicId = "e68f49cb-9b58-49c2-8432-e844f7d13b47"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St, Springfield",
                            DateOfBirth = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            Gender = "Female",
                            HospitalId = 1,
                            IsPublic = false,
                            LastName = "Smith",
                            Name = "Jane",
                            PhoneNumber = "555-5678",
                            PublicId = "3f5754ba-9908-40b2-b385-017475349dbb"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak St, Springfield",
                            DateOfBirth = new DateTime(1978, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex.johnson@example.com",
                            Gender = "Other",
                            HospitalId = 1,
                            IsPublic = false,
                            LastName = "Johnson",
                            Name = "Alex",
                            PhoneNumber = "555-9012",
                            PublicId = "17331303-47a0-4405-b748-99e4c96301ec"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Patients.PatientLabTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CollectedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CollectedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsAbnormal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LabOrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabTestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalRange")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NumericResultValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReceivedByLabAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReportedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LabTestId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientLabTests");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HospitalId = 0,
                            IsPublic = false,
                            Name = "Kabul",
                            PublicId = "db2d6472-2da8-457e-83ba-6fdaf1e0d209"
                        },
                        new
                        {
                            Id = 2,
                            HospitalId = 0,
                            IsPublic = false,
                            Name = "Herat",
                            PublicId = "92e46ae3-df6f-4610-a651-c82a485470be"
                        },
                        new
                        {
                            Id = 3,
                            HospitalId = 0,
                            IsPublic = false,
                            Name = "Kandahar",
                            PublicId = "0fdb8350-1c34-4936-9246-09b3413dd8ea"
                        },
                        new
                        {
                            Id = 4,
                            HospitalId = 0,
                            IsPublic = false,
                            Name = "Balkh",
                            PublicId = "5db313f6-91e3-4244-8e6e-a5e940be62f7"
                        });
                });

            modelBuilder.Entity("SMIS.Domain.Entities.ProvinceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProvinceId", "LanguageId")
                        .IsUnique();

                    b.ToTable("ProvinceTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Kabul",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "کابل",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "کابل",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Herat",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "هرات",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 6,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "هرات",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Kandahar",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 8,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "کندهار",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 9,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "قندهار",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 10,
                            IsDefault = true,
                            LanguageCode = "en",
                            LanguageId = 1,
                            Name = "Balkh",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 11,
                            IsDefault = false,
                            LanguageCode = "ps",
                            LanguageId = 2,
                            Name = "بلخ",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 12,
                            IsDefault = false,
                            LanguageCode = "fa",
                            LanguageId = 3,
                            Name = "بلخ",
                            ProvinceId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Identity.Entity.ApplicationUser", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Hospital", "Hospital")
                        .WithMany("Doctors")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Laboratory.LabTest", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Laboratory.LabTestGroup", "LabTestGroup")
                        .WithMany("LabTests")
                        .HasForeignKey("LabTestGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabTestGroup");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Patients.Patient", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Hospital", "Hospital")
                        .WithMany("Patients")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Patients.PatientLabTest", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Laboratory.LabTest", "LabTest")
                        .WithMany("PatientLabTests")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Patients.Patient", "Patient")
                        .WithMany("PatientLabTests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabTest");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.ProvinceTranslation", b =>
                {
                    b.HasOne("SMIS.Domain.Entities.Localization.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMIS.Domain.Entities.Province", "Province")
                        .WithMany("Translations")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Hospital", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Laboratory.LabTest", b =>
                {
                    b.Navigation("PatientLabTests");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Laboratory.LabTestGroup", b =>
                {
                    b.Navigation("LabTests");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Patients.Patient", b =>
                {
                    b.Navigation("PatientLabTests");
                });

            modelBuilder.Entity("SMIS.Domain.Entities.Province", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
