using System.Reflection;
using SMIS.Application.Attributes;
using SMIS.Application.Repositories.Localization;
using SMIS.Domain.Entities.Localization;

namespace SMIS.Application.Extensions
{
    public static class TranslationKeyUpdateExtensions
    {
        public static async Task AddTranslationKeysForChangedProperties<TDto, TEntity>(
            this ITranslationKeyRepository repository,
            TDto newDto,
            TEntity existingEntity)
        {
            var dtoProperties = typeof(TDto).GetProperties()
                .Where(p => p.GetCustomAttribute<TranslatableAttribute>() != null && p.PropertyType == typeof(string))
                .ToList();

            var entityProperties = typeof(TEntity).GetProperties().ToDictionary(p => p.Name, p => p);

            foreach (var dtoProperty in dtoProperties)
            {
                var newValue = dtoProperty.GetValue(newDto) as string;

                if (!string.IsNullOrEmpty(newValue) && entityProperties.TryGetValue(dtoProperty.Name, out var entityProperty))
                {
                    var oldValue = entityProperty.GetValue(existingEntity) as string;

                    // Only add translation key if value has changed
                    if (newValue != oldValue)
                    {
                        // Check if a translation key with this name already exists (excluding those with empty/null IDs)
                        var existingKey = await repository.GetFirstOrDefaultAsync(tk => tk.Name == newValue && tk.IsActive && !string.IsNullOrEmpty(tk.Id));

                        if (existingKey == null)
                        {
                            // Check if there's already a translation key with this name but inactive
                            var inactiveKey = await repository.GetFirstOrDefaultAsync(tk => tk.Name == newValue && !tk.IsActive && !string.IsNullOrEmpty(tk.Id));

                            if (inactiveKey != null)
                            {
                                // Reactivate the existing key instead of creating a new one
                                inactiveKey.IsActive = true;
                                await repository.UpdateAsync(inactiveKey);
                                await repository.SaveChangesAsync();
                            }
                            else
                            {
                                // Create a new translation key
                                var translationKey = new TranslationKey
                                {
                                    Name = newValue,
                                    IsActive = true
                                    // Note: Id will be generated by the database
                                };
                                await repository.AddAsync(translationKey);
                                await repository.SaveChangesAsync();
                            }
                        }
                    }
                }
            }
        }
    }
}